# rules.toml
[backends]
  [backends.jira]
    [backends.jira.LoadBalancer]
      method = "drr"
    [backends.jira.servers.server]
      url = "http://jira.marathon.localhost:80"
      weight = 1
  [backends.orientdb]
    [backends.orientdb.LoadBalancer]
      method = "drr"
    [backends.orientdb.servers.server]
      url = "http://orientdb.marathon.localhost:80"
      weight = 1      

  [backends.user-service]
    [backends.user-service.LoadBalancer]
      method = "drr"
    [backends.user-service.servers.server]
      url = "http://user-service.marathon.localhost:80"
      weight = 1
  [backends.jira-account-service]
    [backends.jira-account-service.LoadBalancer]
      method = "drr"
    [backends.jira-account-service.servers.server]
      url = "http://jira-account-service.marathon.localhost:80"
      weight = 1
  [backends.ad-account-service]
    [backends.ad-account-service.LoadBalancer]
      method = "drr"
    [backends.ad-account-service.servers.server]
      url = "http://ad-account-service.marathon.localhost:80"
      weight = 1
  [backends.google-apps-service]
    [backends.google-apps-service.LoadBalancer]
      method = "drr"
    [backends.google-apps-service.servers.server]
      url = "http://google-apps-service.marathon.localhost:80"
      weight = 1

[frontends]
  [frontends.jira]
    backend = "jira"
    [frontends.jira.routes.route]
      rule = "Headers"
      value = "X-Host-Override: jira"
  [frontends.orientdb]
    backend = "orientdb"
    [frontends.orientdb.routes.route]
      rule = "Headers"
      value = "X-Host-Override: orientdb"

  [frontends.user-service]
    backend = "user-service"
    [frontends.user-service.routes.route]
      rule = "Headers"
      value = "X-Host-Override: user-service"
  [frontends.jira-account-service]
    backend = "jira-account-service"
    [frontends.jira-account-service.routes.route]
      rule = "Headers"
      value = "X-Host-Override: jira-account-service"
  [frontends.ad-account-service]
    backend = "ad-account-service"
    [frontends.ad-account-service.routes.route]
      rule = "Headers"
      value = "X-Host-Override: ad-account-service"
  [frontends.google-apps-service]
    backend = "google-apps-service"
    [frontends.google-apps-service.routes.route]
      rule = "Headers"
      value = "X-Host-Override: google-apps-service"